name: complex

on: push

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print date on Ubuntu
        run: date

  macos_job:
    runs-on: macos-latest
    steps:
      - name: Print date on macOS
        run: date

  windows_job:
    runs-on: windows-latest
    steps:
      - name: Print date on Windows
        run: date

  dependent_job:
    runs-on: windows-latest
    needs: [ubuntu_job, windows_job, macos_job]
    steps:
      - name: Print date in dependent job
        run: date
